using Mahjong2.Lib.Internals.Yakus;
using Mahjong2.Lib.Internals.Yakus.Impl;

namespace Mahjong2.Lib.Scores;

public enum MjYaku
{
    Riichi,
    DoubleRiichi,
    Tsumo,
    Ippatsu,
    Chankan,
    Rinshan,
    Haitei,
    Houtei,
    Nagashimangan,
    Renhou,
    Pinfu,
    Tanyao,
    Iipeikou,
    Haku,
    Hatsu,
    Chun,
    PlayerWind,
    RoundWind,
    Sanshoku,
    Ittsuu,
    Chanta,
    Honroutou,
    Toitoihou,
    Sanankou,
    Sankantsu,
    Sanshokudoukou,
    Chiitoitsu,
    Shousangen,
    Honitsu,
    Junchan,
    Ryanpeikou,
    Chinitsu,
    Kokushimusou,
    Chuurenpoutou,
    Suuankou,
    Daisangen,
    Shousuushii,
    Daisuushii,
    Ryuuiisou,
    Suukantsu,
    Tsuuiisou,
    Chinroutou,
    Daisharin,
    DaisuushiiDouble,
    Kokushimusou13menmachi,
    SuuankouTanki,
    JunseiChuurenpoutou,
    Tenhou,
    Chiihou,
    RenhouYakuman,
    Dora,
    Uradora,
    Akadora,
}

public record MjYakuResult(MjYaku Yaku, int Han);

internal static class YakuExtensions
{
    public static MjYaku ToMjYaku(this Yaku yaku)
    {
        return yaku switch
        {
            Riichi => MjYaku.Riichi,
            DoubleRiichi => MjYaku.DoubleRiichi,
            Tsumo => MjYaku.Tsumo,
            Ippatsu => MjYaku.Ippatsu,
            Chankan => MjYaku.Chankan,
            Rinshan => MjYaku.Rinshan,
            Haitei => MjYaku.Haitei,
            Houtei => MjYaku.Houtei,
            Nagashimangan => MjYaku.Nagashimangan,
            Renhou => MjYaku.Renhou,
            Pinfu => MjYaku.Pinfu,
            Tanyao => MjYaku.Tanyao,
            Iipeikou => MjYaku.Iipeikou,
            Haku => MjYaku.Haku,
            Hatsu => MjYaku.Hatsu,
            Chun => MjYaku.Chun,
            PlayerWind => MjYaku.PlayerWind,
            RoundWind => MjYaku.RoundWind,
            Sanshoku => MjYaku.Sanshoku,
            Ittsuu => MjYaku.Ittsuu,
            Chanta => MjYaku.Chanta,
            Honroutou => MjYaku.Honroutou,
            Toitoihou => MjYaku.Toitoihou,
            Sanankou => MjYaku.Sanankou,
            Sankantsu => MjYaku.Sankantsu,
            Sanshokudoukou => MjYaku.Sanshokudoukou,
            Chiitoitsu => MjYaku.Chiitoitsu,
            Shousangen => MjYaku.Shousangen,
            Honitsu => MjYaku.Honitsu,
            Junchan => MjYaku.Junchan,
            Ryanpeikou => MjYaku.Ryanpeikou,
            Chinitsu => MjYaku.Chinitsu,
            Kokushimusou => MjYaku.Kokushimusou,
            Chuurenpoutou => MjYaku.Chuurenpoutou,
            Suuankou => MjYaku.Suuankou,
            Daisangen => MjYaku.Daisangen,
            Shousuushii => MjYaku.Shousuushii,
            Daisuushii => MjYaku.Daisuushii,
            Ryuuiisou => MjYaku.Ryuuiisou,
            Suukantsu => MjYaku.Suukantsu,
            Tsuuiisou => MjYaku.Tsuuiisou,
            Chinroutou => MjYaku.Chinroutou,
            Daisharin => MjYaku.Daisharin,
            DaisuushiiDouble => MjYaku.DaisuushiiDouble,
            Kokushimusou13menmachi => MjYaku.Kokushimusou13menmachi,
            SuuankouTanki => MjYaku.SuuankouTanki,
            JunseiChuurenpoutou => MjYaku.JunseiChuurenpoutou,
            Tenhou => MjYaku.Tenhou,
            Chiihou => MjYaku.Chiihou,
            RenhouYakuman => MjYaku.RenhouYakuman,
            Dora => MjYaku.Dora,
            Uradora => MjYaku.Uradora,
            Akadora => MjYaku.Akadora,
            _ => throw new NotImplementedException(),
        };
    }
}