name: .NET テスト実行

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: ビルドとテスト (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: .NET SDK セットアップ
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          10.0.x
    
    - name: 依存関係の復元
      run: dotnet restore src/Mahjong2.sln
    
    - name: ビルド
      run: dotnet build src/Mahjong2.sln --configuration Release --no-restore
    
    - name: テスト実行
      run: dotnet test src/Mahjong2.sln --configuration Release --no-restore --no-build --verbosity normal